export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  STORE_NOT_FOUND: "STORE_NOT_FOUND",
  STORE_INACTIVE: "STORE_INACTIVE",
  TENANT_ACCESS_DENIED: "TENANT_ACCESS_DENIED",
  INVALID_API_KEY: "INVALID_API_KEY",
  INVALID_SECRET_KEY: "INVALID_SECRET_KEY",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  CONFLICT: "CONFLICT",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_STATE: "INVALID_STATE",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
