import { ERROR_CODES, type ErrorCode } from "@/shared/constants/error-codes";

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];

export const ERROR_HTTP_STATUS: Record<ErrorCode, HttpStatus> = {
  [ERROR_CODES.VALIDATION_ERROR]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.UNAUTHORIZED]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.FORBIDDEN]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.STORE_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.STORE_INACTIVE]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.TENANT_ACCESS_DENIED]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.INVALID_API_KEY]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.INVALID_SECRET_KEY]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.DUPLICATE_RESOURCE]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.CONFLICT]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.INSUFFICIENT_STOCK]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.INVALID_STATE]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.RATE_LIMITED]: HTTP_STATUS.TOO_MANY_REQUESTS,
  [ERROR_CODES.INTERNAL_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
};
