import type { DemoStoreSeed, SeedProductDef } from "./types";

function inr(rupees: number): number {
  return Math.round(rupees * 100);
}

function product(input: {
  title: string;
  handle: string;
  blurb: string;
  categorySlug: string;
  collections?: string[];
  skuPrefix: string;
  variants: Array<{
    suffix: string;
    title: string;
    price: number;
    compareAt?: number;
    qty?: number;
  }>;
}): SeedProductDef {
  return {
    title: input.title,
    handle: input.handle,
    shortDescription: input.blurb,
    description: `${input.blurb} Sold exclusively through this demo storefront. Prices in INR (stored as paise).`,
    categorySlug: input.categorySlug,
    collectionSlugs: input.collections ?? ["featured"],
    variants: input.variants.map((v) => ({
      sku: `${input.skuPrefix}-${v.suffix}`,
      title: v.title,
      pricePaise: inr(v.price),
      compareAtPricePaise: v.compareAt !== undefined ? inr(v.compareAt) : undefined,
      availableQuantity: v.qty ?? 50,
    })),
  };
}

/** Deterministic stock so seed is stable across runs. */
function stock(n: number): number {
  return n;
}

const technovaProducts: SeedProductDef[] = [
  product({
    title: "NovaBuds Pro Wireless Earbuds",
    handle: "novabuds-pro",
    blurb: "ANC earbuds with 32-hour case battery and USB-C fast charge.",
    categorySlug: "audio",
    collections: ["featured", "new-arrivals"],
    skuPrefix: "TN-EAR",
    variants: [
      { suffix: "BLK", title: "Black", price: 6999, compareAt: 7999, qty: stock(85) },
      { suffix: "WHT", title: "White", price: 6999, compareAt: 7999, qty: stock(60) },
    ],
  }),
  product({
    title: "PulseWatch X Smartwatch",
    handle: "pulsewatch-x",
    blurb: "AMOLED fitness watch with SpO2, GPS, and 7-day battery.",
    categorySlug: "wearables",
    collections: ["featured"],
    skuPrefix: "TN-WATCH",
    variants: [
      { suffix: "42-BLK", title: "42mm / Black", price: 12999, compareAt: 14999, qty: stock(45) },
      { suffix: "46-SLV", title: "46mm / Silver", price: 13999, compareAt: 15999, qty: stock(38) },
    ],
  }),
  product({
    title: "AeroBook 14 Laptop Sleeve",
    handle: "aerobook-14-sleeve",
    blurb: "Water-resistant neoprene sleeve for 14-inch notebooks.",
    categorySlug: "accessories",
    skuPrefix: "TN-SLV",
    variants: [{ suffix: "GRY", title: "Graphite", price: 1499, qty: stock(120) }],
  }),
  product({
    title: "ChargeDock MagSafe Stand",
    handle: "chargedock-magsafe",
    blurb: "2-in-1 MagSafe phone + AirPods charging stand.",
    categorySlug: "accessories",
    collections: ["new-arrivals"],
    skuPrefix: "TN-DOC",
    variants: [{ suffix: "WHT", title: "White", price: 3499, compareAt: 3999, qty: stock(70) }],
  }),
  product({
    title: "SonicBar Mini Bluetooth Speaker",
    handle: "sonicbar-mini",
    blurb: "Portable IPX7 speaker with deep bass and 12-hour playtime.",
    categorySlug: "audio",
    skuPrefix: "TN-SPK",
    variants: [
      { suffix: "BLU", title: "Ocean Blue", price: 2499, qty: stock(95) },
      { suffix: "RED", title: "Crimson", price: 2499, qty: stock(80) },
    ],
  }),
  product({
    title: "UltraThin Power Bank 20000mAh",
    handle: "ultrathin-powerbank-20k",
    blurb: "65W PD power bank with dual USB-C and LED indicator.",
    categorySlug: "power",
    collections: ["featured"],
    skuPrefix: "TN-PB",
    variants: [{ suffix: "20K", title: "20000mAh", price: 4299, compareAt: 4999, qty: stock(110) }],
  }),
  product({
    title: "FlexiCam 4K Webcam",
    handle: "flexicam-4k",
    blurb: "Autofocus 4K webcam with dual mics for remote work.",
    categorySlug: "computers",
    skuPrefix: "TN-CAM",
    variants: [{ suffix: "4K", title: "Standard", price: 5999, qty: stock(55) }],
  }),
  product({
    title: "TypeFast Mechanical Keyboard",
    handle: "typefast-mech-keyboard",
    blurb: "Hot-swappable 75% keyboard with RGB and PBT keycaps.",
    categorySlug: "computers",
    collections: ["featured", "new-arrivals"],
    skuPrefix: "TN-KB",
    variants: [
      { suffix: "RED", title: "Red switches", price: 7499, qty: stock(40) },
      { suffix: "BRN", title: "Brown switches", price: 7499, qty: stock(42) },
    ],
  }),
  product({
    title: "Precision Pro Mouse",
    handle: "precision-pro-mouse",
    blurb: "Ergonomic wireless mouse with 8K polling and silent clicks.",
    categorySlug: "computers",
    skuPrefix: "TN-MSE",
    variants: [{ suffix: "BLK", title: "Black", price: 3999, compareAt: 4499, qty: stock(75) }],
  }),
  product({
    title: "StreamLight Ring Lamp",
    handle: "streamlight-ring",
    blurb: "10-inch ring light with tripod and phone clamp.",
    categorySlug: "accessories",
    skuPrefix: "TN-RING",
    variants: [{ suffix: "10", title: "10 inch", price: 1899, qty: stock(90) }],
  }),
  product({
    title: "NovaTab S8 Stylus",
    handle: "novatab-s8-stylus",
    blurb: "Pressure-sensitive active stylus for tablets and notebooks.",
    categorySlug: "accessories",
    skuPrefix: "TN-STY",
    variants: [{ suffix: "GRY", title: "Space Grey", price: 2799, qty: stock(65) }],
  }),
  product({
    title: "MeshWiFi Duo Pack",
    handle: "meshwifi-duo",
    blurb: "AX3000 dual-band mesh Wi-Fi 6 system for whole-home coverage.",
    categorySlug: "networking",
    collections: ["featured"],
    skuPrefix: "TN-MESH",
    variants: [{ suffix: "DUO", title: "2-pack", price: 11999, compareAt: 13999, qty: stock(30) }],
  }),
  product({
    title: "SecureCam Outdoor 2K",
    handle: "securecam-outdoor-2k",
    blurb: "Weatherproof security camera with color night vision.",
    categorySlug: "smart-home",
    skuPrefix: "TN-CAMO",
    variants: [{ suffix: "2K", title: "2K", price: 5499, qty: stock(48) }],
  }),
  product({
    title: "SmartPlug Energy Monitor",
    handle: "smartplug-energy",
    blurb: "Wi-Fi smart plug with real-time power monitoring.",
    categorySlug: "smart-home",
    collections: ["new-arrivals"],
    skuPrefix: "TN-PLUG",
    variants: [{ suffix: "1P", title: "Single pack", price: 999, qty: stock(200) }],
  }),
  product({
    title: "VaultDrive 1TB SSD",
    handle: "vaultdrive-1tb",
    blurb: "USB 3.2 Gen2 portable SSD up to 1050 MB/s.",
    categorySlug: "storage",
    skuPrefix: "TN-SSD",
    variants: [
      { suffix: "1TB", title: "1TB", price: 8999, compareAt: 9999, qty: stock(50) },
      { suffix: "2TB", title: "2TB", price: 14999, compareAt: 16999, qty: stock(25) },
    ],
  }),
  product({
    title: "CableKit Pro Braided Set",
    handle: "cablekit-pro",
    blurb: "6-piece braided cable kit with USB-C, Lightning adapters.",
    categorySlug: "accessories",
    skuPrefix: "TN-CBL",
    variants: [{ suffix: "6PK", title: "6-piece", price: 1299, qty: stock(150) }],
  }),
  product({
    title: "DeskMat XL Gaming Pad",
    handle: "deskmat-xl",
    blurb: "Extended anti-slip desk mat with stitched edges.",
    categorySlug: "accessories",
    skuPrefix: "TN-MAT",
    variants: [
      { suffix: "BLK", title: "Black", price: 1499, qty: stock(100) },
      { suffix: "NVY", title: "Navy", price: 1499, qty: stock(80) },
    ],
  }),
  product({
    title: "NoiseShield Gaming Headset",
    handle: "noiseshield-headset",
    blurb: "7.1 surround headset with detachable boom mic.",
    categorySlug: "audio",
    collections: ["featured"],
    skuPrefix: "TN-HS",
    variants: [{ suffix: "BLK", title: "Black", price: 4599, compareAt: 5299, qty: stock(58) }],
  }),
  product({
    title: "PixelFrame Digital Photo Frame",
    handle: "pixelframe-10",
    blurb: "10-inch Wi-Fi photo frame with cloud sync.",
    categorySlug: "smart-home",
    skuPrefix: "TN-FRAME",
    variants: [{ suffix: "10", title: "10 inch", price: 7999, qty: stock(35) }],
  }),
  product({
    title: "ThermoSense Smart Thermostat",
    handle: "thermosense-thermostat",
    blurb: "App-controlled thermostat with scheduling and energy reports.",
    categorySlug: "smart-home",
    collections: ["new-arrivals"],
    skuPrefix: "TN-THERM",
    variants: [{ suffix: "WHT", title: "White", price: 9999, compareAt: 11999, qty: stock(28) }],
  }),
  product({
    title: "HubCast 4K Streaming Stick",
    handle: "hubcast-4k",
    blurb: "4K HDR streaming stick with dual-band Wi-Fi and voice remote.",
    categorySlug: "smart-home",
    skuPrefix: "TN-CAST",
    variants: [{ suffix: "4K", title: "4K", price: 4499, qty: stock(72) }],
  }),
];

const urbanThreadProducts: SeedProductDef[] = [
  product({
    title: "CityLine Oxford Shirt",
    handle: "cityline-oxford-shirt",
    blurb: "Breathable cotton oxford shirt for everyday office wear.",
    categorySlug: "shirts",
    collections: ["featured"],
    skuPrefix: "UT-SHIRT",
    variants: [
      { suffix: "M-WHT", title: "M / White", price: 1799, qty: stock(60) },
      { suffix: "L-WHT", title: "L / White", price: 1799, qty: stock(55) },
      { suffix: "M-BLU", title: "M / Sky Blue", price: 1799, qty: stock(48) },
    ],
  }),
  product({
    title: "Metro Slim Chinos",
    handle: "metro-slim-chinos",
    blurb: "Stretch slim-fit chinos with hidden elastic waist.",
    categorySlug: "bottoms",
    collections: ["featured", "bestsellers"],
    skuPrefix: "UT-CHINO",
    variants: [
      { suffix: "32-BGE", title: "32 / Beige", price: 2299, compareAt: 2699, qty: stock(40) },
      { suffix: "34-NVY", title: "34 / Navy", price: 2299, compareAt: 2699, qty: stock(42) },
    ],
  }),
  product({
    title: "Aether Soft Hoodie",
    handle: "aether-soft-hoodie",
    blurb: "Brushed fleece hoodie with kangaroo pocket.",
    categorySlug: "outerwear",
    skuPrefix: "UT-HOOD",
    variants: [
      { suffix: "M-GRY", title: "M / Heather Grey", price: 2499, qty: stock(70) },
      { suffix: "L-BLK", title: "L / Black", price: 2499, qty: stock(65) },
    ],
  }),
  product({
    title: "Lumen Linen Kurta",
    handle: "lumen-linen-kurta",
    blurb: "Relaxed linen-blend kurta for festive and casual looks.",
    categorySlug: "ethnic",
    collections: ["new-arrivals"],
    skuPrefix: "UT-KURTA",
    variants: [
      { suffix: "M-IVY", title: "M / Ivory", price: 1999, qty: stock(50) },
      { suffix: "L-OLV", title: "L / Olive", price: 1999, qty: stock(45) },
    ],
  }),
  product({
    title: "Stride Denim Jacket",
    handle: "stride-denim-jacket",
    blurb: "Classic trucker jacket in mid-wash denim.",
    categorySlug: "outerwear",
    collections: ["bestsellers"],
    skuPrefix: "UT-DENIM",
    variants: [
      { suffix: "M", title: "M", price: 3499, compareAt: 3999, qty: stock(35) },
      { suffix: "L", title: "L", price: 3499, compareAt: 3999, qty: stock(32) },
    ],
  }),
  product({
    title: "Nova Knit Polo",
    handle: "nova-knit-polo",
    blurb: "Pique knit polo with contrast collar tipping.",
    categorySlug: "shirts",
    skuPrefix: "UT-POLO",
    variants: [
      { suffix: "M-NVY", title: "M / Navy", price: 1599, qty: stock(80) },
      { suffix: "L-GRN", title: "L / Forest", price: 1599, qty: stock(70) },
    ],
  }),
  product({
    title: "Harbor Cargo Pants",
    handle: "harbor-cargo-pants",
    blurb: "Utility cargo pants with multiple pockets.",
    categorySlug: "bottoms",
    skuPrefix: "UT-CARGO",
    variants: [
      { suffix: "32-OLV", title: "32 / Olive", price: 2599, qty: stock(38) },
      { suffix: "34-BLK", title: "34 / Black", price: 2599, qty: stock(40) },
    ],
  }),
  product({
    title: "SilkRoute Scarf",
    handle: "silkroute-scarf",
    blurb: "Lightweight printed scarf in soft modal fabric.",
    categorySlug: "accessories",
    collections: ["new-arrivals"],
    skuPrefix: "UT-SCARF",
    variants: [{ suffix: "PRT", title: "Print A", price: 999, qty: stock(100) }],
  }),
  product({
    title: "Urban Belt Classic",
    handle: "urban-belt-classic",
    blurb: "Full-grain leather belt with brushed buckle.",
    categorySlug: "accessories",
    skuPrefix: "UT-BELT",
    variants: [
      { suffix: "34-BRN", title: "34 / Brown", price: 1299, qty: stock(55) },
      { suffix: "36-BLK", title: "36 / Black", price: 1299, qty: stock(60) },
    ],
  }),
  product({
    title: "CloudSoft Crew Tee",
    handle: "cloudsoft-crew-tee",
    blurb: "Supima cotton crew neck tee with clean finish.",
    categorySlug: "tees",
    collections: ["featured", "bestsellers"],
    skuPrefix: "UT-TEE",
    variants: [
      { suffix: "M-WHT", title: "M / White", price: 899, qty: stock(120) },
      { suffix: "L-BLK", title: "L / Black", price: 899, qty: stock(110) },
      { suffix: "M-GRY", title: "M / Grey", price: 899, qty: stock(95) },
    ],
  }),
  product({
    title: "Evening Wrap Dress",
    handle: "evening-wrap-dress",
    blurb: "Flowy wrap dress with adjustable waist tie.",
    categorySlug: "dresses",
    collections: ["featured"],
    skuPrefix: "UT-DRESS",
    variants: [
      { suffix: "S-BLK", title: "S / Black", price: 2999, qty: stock(28) },
      { suffix: "M-NVY", title: "M / Navy", price: 2999, qty: stock(30) },
    ],
  }),
  product({
    title: "Trail Runner Sneakers",
    handle: "trail-runner-sneakers",
    blurb: "Lightweight knit sneakers with cushioned sole.",
    categorySlug: "footwear",
    collections: ["bestsellers"],
    skuPrefix: "UT-SNK",
    variants: [
      { suffix: "8-WHT", title: "UK 8 / White", price: 3999, compareAt: 4499, qty: stock(40) },
      { suffix: "9-BLK", title: "UK 9 / Black", price: 3999, compareAt: 4499, qty: stock(38) },
    ],
  }),
  product({
    title: "Monsoon Packable Jacket",
    handle: "monsoon-packable-jacket",
    blurb: "Water-repellent packable windbreaker.",
    categorySlug: "outerwear",
    skuPrefix: "UT-WIND",
    variants: [
      { suffix: "M-YLW", title: "M / Yellow", price: 2799, qty: stock(33) },
      { suffix: "L-BLK", title: "L / Black", price: 2799, qty: stock(36) },
    ],
  }),
  product({
    title: "Atelier Pleated Skirt",
    handle: "atelier-pleated-skirt",
    blurb: "Midi pleated skirt with elastic back waist.",
    categorySlug: "bottoms",
    collections: ["new-arrivals"],
    skuPrefix: "UT-SKIRT",
    variants: [
      { suffix: "S-BGE", title: "S / Beige", price: 2199, qty: stock(25) },
      { suffix: "M-BLK", title: "M / Black", price: 2199, qty: stock(27) },
    ],
  }),
  product({
    title: "Canvas Weekender Tote",
    handle: "canvas-weekender-tote",
    blurb: "Heavy canvas tote with leather handles.",
    categorySlug: "accessories",
    skuPrefix: "UT-TOTE",
    variants: [{ suffix: "NAT", title: "Natural", price: 1899, qty: stock(70) }],
  }),
  product({
    title: "Heritage Wool Blazer",
    handle: "heritage-wool-blazer",
    blurb: "Structured single-breasted blazer for smart-casual looks.",
    categorySlug: "outerwear",
    collections: ["featured"],
    skuPrefix: "UT-BLAZ",
    variants: [
      { suffix: "40-NVY", title: "40 / Navy", price: 5999, compareAt: 6999, qty: stock(20) },
      { suffix: "42-GRY", title: "42 / Charcoal", price: 5999, compareAt: 6999, qty: stock(18) },
    ],
  }),
  product({
    title: "Everyday Ankle Socks 3-Pack",
    handle: "everyday-ankle-socks",
    blurb: "Breathable cotton-blend ankle socks, pack of 3.",
    categorySlug: "accessories",
    skuPrefix: "UT-SOCK",
    variants: [{ suffix: "3PK", title: "3-pack / Assorted", price: 499, qty: stock(200) }],
  }),
  product({
    title: "Studio Yoga Leggings",
    handle: "studio-yoga-leggings",
    blurb: "High-waist compression leggings with phone pocket.",
    categorySlug: "activewear",
    collections: ["bestsellers"],
    skuPrefix: "UT-LEG",
    variants: [
      { suffix: "S-BLK", title: "S / Black", price: 1699, qty: stock(55) },
      { suffix: "M-NVY", title: "M / Navy", price: 1699, qty: stock(50) },
    ],
  }),
  product({
    title: "Coastal Linen Shirt Dress",
    handle: "coastal-linen-shirt-dress",
    blurb: "Breezy shirt dress with side slits and belt.",
    categorySlug: "dresses",
    skuPrefix: "UT-SDR",
    variants: [
      { suffix: "S-WHT", title: "S / White", price: 2699, qty: stock(22) },
      { suffix: "M-SAGE", title: "M / Sage", price: 2699, qty: stock(24) },
    ],
  }),
  product({
    title: "NightShift Pyjama Set",
    handle: "nightshift-pyjama-set",
    blurb: "Soft cotton pyjama set with piping detail.",
    categorySlug: "loungewear",
    collections: ["new-arrivals"],
    skuPrefix: "UT-PJ",
    variants: [
      { suffix: "M-NVY", title: "M / Navy stripe", price: 1899, qty: stock(40) },
      { suffix: "L-GRY", title: "L / Grey", price: 1899, qty: stock(38) },
    ],
  }),
];

const fitZoneProducts: SeedProductDef[] = [
  product({
    title: "IronGrip Adjustable Dumbbells",
    handle: "irongrip-adjustable-dumbbells",
    blurb: "Pair of adjustable dumbbells from 2.5 to 24 kg.",
    categorySlug: "strength",
    collections: ["featured"],
    skuPrefix: "FZ-DB",
    variants: [{ suffix: "24KG", title: "2.5–24 kg pair", price: 12999, compareAt: 14999, qty: stock(25) }],
  }),
  product({
    title: "FlexBand Resistance Set",
    handle: "flexband-resistance-set",
    blurb: "5-level latex resistance bands with carry pouch.",
    categorySlug: "strength",
    collections: ["bestsellers"],
    skuPrefix: "FZ-BAND",
    variants: [{ suffix: "5PK", title: "5-pack", price: 999, qty: stock(150) }],
  }),
  product({
    title: "PacePro Running Shoes",
    handle: "pacepro-running-shoes",
    blurb: "Cushioned road runners with breathable mesh upper.",
    categorySlug: "footwear",
    collections: ["featured", "new-arrivals"],
    skuPrefix: "FZ-RUN",
    variants: [
      { suffix: "8-BLU", title: "UK 8 / Blue", price: 4499, compareAt: 4999, qty: stock(45) },
      { suffix: "9-BLK", title: "UK 9 / Black", price: 4499, compareAt: 4999, qty: stock(42) },
    ],
  }),
  product({
    title: "CoreMat Pro Yoga Mat",
    handle: "coremat-pro",
    blurb: "6mm TPE non-slip yoga mat with alignment marks.",
    categorySlug: "yoga",
    skuPrefix: "FZ-MAT",
    variants: [
      { suffix: "PRL", title: "Purple", price: 1499, qty: stock(80) },
      { suffix: "TEAL", title: "Teal", price: 1499, qty: stock(75) },
    ],
  }),
  product({
    title: "HydroFuel Insulated Bottle 1L",
    handle: "hydrofuel-bottle-1l",
    blurb: "Stainless steel vacuum bottle keeps drinks cold 24h.",
    categorySlug: "accessories",
    collections: ["bestsellers"],
    skuPrefix: "FZ-BTL",
    variants: [
      { suffix: "BLK", title: "Matte Black", price: 1299, qty: stock(110) },
      { suffix: "SLV", title: "Steel", price: 1299, qty: stock(95) },
    ],
  }),
  product({
    title: "JumpRope Speed Cable",
    handle: "jumprope-speed",
    blurb: "Adjustable steel-cable speed rope for HIIT.",
    categorySlug: "cardio",
    skuPrefix: "FZ-ROPE",
    variants: [{ suffix: "SPD", title: "Speed", price: 699, qty: stock(130) }],
  }),
  product({
    title: "LiftBelt Lumbar Support",
    handle: "liftbelt-lumbar",
    blurb: "Padded weightlifting belt with double prong buckle.",
    categorySlug: "strength",
    skuPrefix: "FZ-BELT",
    variants: [
      { suffix: "M", title: "Medium", price: 1899, qty: stock(40) },
      { suffix: "L", title: "Large", price: 1899, qty: stock(38) },
    ],
  }),
  product({
    title: "Pulse Heart Rate Armband",
    handle: "pulse-hr-armband",
    blurb: "Optical HR armband compatible with major fitness apps.",
    categorySlug: "wearables",
    collections: ["new-arrivals"],
    skuPrefix: "FZ-HR",
    variants: [{ suffix: "BLK", title: "Black", price: 3499, qty: stock(50) }],
  }),
  product({
    title: "Agility Ladder 4m",
    handle: "agility-ladder-4m",
    blurb: "Flat-rung agility ladder with carry bag.",
    categorySlug: "cardio",
    skuPrefix: "FZ-LAD",
    variants: [{ suffix: "4M", title: "4 metre", price: 899, qty: stock(70) }],
  }),
  product({
    title: "FoamRoll Deep Tissue",
    handle: "foamroll-deep",
    blurb: "High-density foam roller for recovery sessions.",
    categorySlug: "recovery",
    skuPrefix: "FZ-ROLL",
    variants: [{ suffix: "45", title: "45 cm", price: 1199, qty: stock(85) }],
  }),
  product({
    title: "GripChalk Liquid 100ml",
    handle: "gripchalk-liquid",
    blurb: "Quick-dry liquid chalk for lifts and climbing.",
    categorySlug: "accessories",
    skuPrefix: "FZ-CHALK",
    variants: [{ suffix: "100", title: "100 ml", price: 449, qty: stock(160) }],
  }),
  product({
    title: "KettleBell Cast Iron 16kg",
    handle: "kettlebell-16kg",
    blurb: "Powder-coated cast iron kettlebell.",
    categorySlug: "strength",
    collections: ["featured"],
    skuPrefix: "FZ-KB",
    variants: [
      { suffix: "12", title: "12 kg", price: 2499, qty: stock(30) },
      { suffix: "16", title: "16 kg", price: 2999, qty: stock(28) },
    ],
  }),
  product({
    title: "TrailPack Hydration Vest",
    handle: "trailpack-hydration",
    blurb: "Lightweight running vest with 1.5L bladder.",
    categorySlug: "accessories",
    skuPrefix: "FZ-VEST",
    variants: [{ suffix: "S-M", title: "S/M", price: 3999, qty: stock(35) }],
  }),
  product({
    title: "BalanceBoard Stability Trainer",
    handle: "balanceboard-stability",
    blurb: "Wooden wobble board for core and ankle strength.",
    categorySlug: "recovery",
    skuPrefix: "FZ-BAL",
    variants: [{ suffix: "STD", title: "Standard", price: 2199, qty: stock(40) }],
  }),
  product({
    title: "Sprint Cap DryFit",
    handle: "sprint-cap-dryfit",
    blurb: "Moisture-wicking running cap with reflective logo.",
    categorySlug: "apparel",
    skuPrefix: "FZ-CAP",
    variants: [
      { suffix: "BLK", title: "Black", price: 599, qty: stock(100) },
      { suffix: "NVY", title: "Navy", price: 599, qty: stock(90) },
    ],
  }),
  product({
    title: "PowerRack Pull-Up Bar",
    handle: "powerrack-pullup",
    blurb: "Doorway pull-up bar with multi-grip positions.",
    categorySlug: "strength",
    skuPrefix: "FZ-PULL",
    variants: [{ suffix: "DR", title: "Doorway", price: 1799, qty: stock(55) }],
  }),
  product({
    title: "CycleGloves Gel Padded",
    handle: "cyclegloves-gel",
    blurb: "Breathable cycling gloves with gel palm padding.",
    categorySlug: "apparel",
    collections: ["bestsellers"],
    skuPrefix: "FZ-GLV",
    variants: [
      { suffix: "M", title: "Medium", price: 799, qty: stock(60) },
      { suffix: "L", title: "Large", price: 799, qty: stock(58) },
    ],
  }),
  product({
    title: "Interval Timer Cube",
    handle: "interval-timer-cube",
    blurb: "Flip timer cube for HIIT and kitchen workouts.",
    categorySlug: "accessories",
    skuPrefix: "FZ-TMR",
    variants: [{ suffix: "CUBE", title: "Cube", price: 999, qty: stock(75) }],
  }),
  product({
    title: "ColdPack Recovery Wrap",
    handle: "coldpack-recovery-wrap",
    blurb: "Reusable gel cold/hot wrap for joints.",
    categorySlug: "recovery",
    collections: ["new-arrivals"],
    skuPrefix: "FZ-COLD",
    variants: [{ suffix: "WRAP", title: "Wrap", price: 699, qty: stock(90) }],
  }),
  product({
    title: "SlamBall 10kg",
    handle: "slamball-10kg",
    blurb: "Dead-bounce slam ball for conditioning circuits.",
    categorySlug: "strength",
    skuPrefix: "FZ-SLAM",
    variants: [
      { suffix: "8", title: "8 kg", price: 1899, qty: stock(30) },
      { suffix: "10", title: "10 kg", price: 2199, qty: stock(28) },
    ],
  }),
  product({
    title: "SwimGoggles AntiFog Pro",
    handle: "swimgoggles-antifog",
    blurb: "UV-protected swim goggles with soft silicone seal.",
    categorySlug: "aquatic",
    skuPrefix: "FZ-GOG",
    variants: [{ suffix: "CLR", title: "Clear lens", price: 899, qty: stock(85) }],
  }),
];

const bookNestProducts: SeedProductDef[] = [
  product({
    title: "The Quiet Algorithm",
    handle: "quiet-algorithm",
    blurb: "A thriller about AI ethics set in Bengaluru startups.",
    categorySlug: "fiction",
    collections: ["featured", "bestsellers"],
    skuPrefix: "BN-FIC",
    variants: [{ suffix: "PB", title: "Paperback", price: 499, qty: stock(80) }],
  }),
  product({
    title: "Monsoon Notebook A5 Dotted",
    handle: "monsoon-notebook-a5",
    blurb: "160-page dotted notebook with lay-flat binding.",
    categorySlug: "stationery",
    collections: ["bestsellers"],
    skuPrefix: "BN-NB",
    variants: [
      { suffix: "A5-NVY", title: "A5 / Navy", price: 349, qty: stock(150) },
      { suffix: "A5-CRT", title: "A5 / Cream", price: 349, qty: stock(140) },
    ],
  }),
  product({
    title: "InkWell Fountain Pen Set",
    handle: "inkwell-fountain-set",
    blurb: "Beginner fountain pen with converter and blue ink.",
    categorySlug: "stationery",
    collections: ["featured"],
    skuPrefix: "BN-PEN",
    variants: [{ suffix: "SET", title: "Set", price: 1299, compareAt: 1499, qty: stock(60) }],
  }),
  product({
    title: "Atlas of Indian Birds",
    handle: "atlas-indian-birds",
    blurb: "Illustrated field guide covering 200+ bird species.",
    categorySlug: "non-fiction",
    skuPrefix: "BN-NF",
    variants: [{ suffix: "HC", title: "Hardcover", price: 1499, qty: stock(40) }],
  }),
  product({
    title: "Kids First Coding Stories",
    handle: "kids-first-coding",
    blurb: "Picture book introducing loops and conditionals playfully.",
    categorySlug: "children",
    collections: ["new-arrivals"],
    skuPrefix: "BN-KID",
    variants: [{ suffix: "PB", title: "Paperback", price: 399, qty: stock(90) }],
  }),
  product({
    title: "Desk Planner 2026",
    handle: "desk-planner-2026",
    blurb: "Weekly desk planner with goal trackers and stickers.",
    categorySlug: "stationery",
    skuPrefix: "BN-PLN",
    variants: [{ suffix: "2026", title: "2026 edition", price: 599, qty: stock(100) }],
  }),
  product({
    title: "Poetry of Rainy Evenings",
    handle: "poetry-rainy-evenings",
    blurb: "Contemporary Indian poetry anthology.",
    categorySlug: "fiction",
    skuPrefix: "BN-POE",
    variants: [{ suffix: "PB", title: "Paperback", price: 299, qty: stock(70) }],
  }),
  product({
    title: "Startup Finance Playbook",
    handle: "startup-finance-playbook",
    blurb: "Practical guide to unit economics and fundraising.",
    categorySlug: "business",
    collections: ["bestsellers"],
    skuPrefix: "BN-BIZ",
    variants: [{ suffix: "PB", title: "Paperback", price: 699, qty: stock(55) }],
  }),
  product({
    title: "Highlight Marker Duo Pack",
    handle: "highlight-marker-duo",
    blurb: "Pastel dual-tip highlighters, pack of 6.",
    categorySlug: "stationery",
    skuPrefix: "BN-HL",
    variants: [{ suffix: "6PK", title: "6-pack", price: 249, qty: stock(200) }],
  }),
  product({
    title: "World History Timeline Chart",
    handle: "world-history-timeline",
    blurb: "Fold-out timeline poster for students.",
    categorySlug: "education",
    skuPrefix: "BN-EDU",
    variants: [{ suffix: "PST", title: "Poster", price: 199, qty: stock(80) }],
  }),
  product({
    title: "CraftPaper Scrapbook Kit",
    handle: "craftpaper-scrapbook",
    blurb: "Scrapbook kit with patterned papers and washi tapes.",
    categorySlug: "stationery",
    collections: ["new-arrivals"],
    skuPrefix: "BN-SCRAP",
    variants: [{ suffix: "KIT", title: "Kit", price: 899, qty: stock(45) }],
  }),
  product({
    title: "Mystery at Marine Drive",
    handle: "mystery-marine-drive",
    blurb: "Mumbai noir detective novel.",
    categorySlug: "fiction",
    collections: ["featured"],
    skuPrefix: "BN-MYST",
    variants: [{ suffix: "PB", title: "Paperback", price: 450, qty: stock(65) }],
  }),
  product({
    title: "Mindful Mornings Journal",
    handle: "mindful-mornings-journal",
    blurb: "Guided gratitude and habit journal for 90 days.",
    categorySlug: "wellness",
    skuPrefix: "BN-JRN",
    variants: [{ suffix: "90", title: "90-day", price: 549, qty: stock(75) }],
  }),
  product({
    title: "STEM Experiments for Teens",
    handle: "stem-experiments-teens",
    blurb: "Hands-on science experiments with household materials.",
    categorySlug: "education",
    collections: ["bestsellers"],
    skuPrefix: "BN-STEM",
    variants: [{ suffix: "PB", title: "Paperback", price: 599, qty: stock(50) }],
  }),
  product({
    title: "Bookstand Bamboo Adjustable",
    handle: "bookstand-bamboo",
    blurb: "Adjustable bamboo reading stand for desks.",
    categorySlug: "accessories",
    skuPrefix: "BN-STAND",
    variants: [{ suffix: "BAM", title: "Bamboo", price: 1199, qty: stock(40) }],
  }),
  product({
    title: "Classic Myths Retold",
    handle: "classic-myths-retold",
    blurb: "Illustrated retellings of Indian epics for young readers.",
    categorySlug: "children",
    skuPrefix: "BN-MYTH",
    variants: [{ suffix: "HC", title: "Hardcover", price: 799, qty: stock(35) }],
  }),
  product({
    title: "Architect Sketch Pad A3",
    handle: "architect-sketch-a3",
    blurb: "Heavyweight sketch pad, 50 sheets, acid-free.",
    categorySlug: "stationery",
    skuPrefix: "BN-SKA3",
    variants: [{ suffix: "A3", title: "A3", price: 449, qty: stock(60) }],
  }),
  product({
    title: "CookLikeHome Regional Recipes",
    handle: "cooklikehome-regional",
    blurb: "Home-style recipes across Indian regions.",
    categorySlug: "non-fiction",
    collections: ["featured"],
    skuPrefix: "BN-COOK",
    variants: [{ suffix: "HC", title: "Hardcover", price: 999, qty: stock(42) }],
  }),
  product({
    title: "Desk Organizer Mesh 5-Tray",
    handle: "desk-organizer-mesh",
    blurb: "Metal mesh desk organizer for pens and sticky notes.",
    categorySlug: "accessories",
    skuPrefix: "BN-ORG",
    variants: [{ suffix: "BLK", title: "Black", price: 699, qty: stock(70) }],
  }),
  product({
    title: "Language Lab Hindi Workbook",
    handle: "language-lab-hindi",
    blurb: "Beginner Hindi workbook with QR audio lessons.",
    categorySlug: "education",
    collections: ["new-arrivals"],
    skuPrefix: "BN-HIN",
    variants: [{ suffix: "WB", title: "Workbook", price: 399, qty: stock(55) }],
  }),
  product({
    title: "Bookmark Leather Trio",
    handle: "bookmark-leather-trio",
    blurb: "Hand-stitched leather bookmarks, set of 3.",
    categorySlug: "accessories",
    skuPrefix: "BN-BM",
    variants: [{ suffix: "3PK", title: "3-pack", price: 349, qty: stock(120) }],
  }),
];

const littlePlayProducts: SeedProductDef[] = [
  product({
    title: "BuildBox Wooden Blocks 50pc",
    handle: "buildbox-wooden-blocks",
    blurb: "Natural wood building blocks for ages 3+.",
    categorySlug: "building",
    collections: ["featured", "bestsellers"],
    skuPrefix: "LP-BLK",
    variants: [{ suffix: "50", title: "50 pieces", price: 1499, qty: stock(70) }],
  }),
  product({
    title: "Rainbow Stacking Rings",
    handle: "rainbow-stacking-rings",
    blurb: "Classic stacking toy with soft edges.",
    categorySlug: "preschool",
    skuPrefix: "LP-RING",
    variants: [{ suffix: "STD", title: "Standard", price: 699, qty: stock(90) }],
  }),
  product({
    title: "Adventure Doll House",
    handle: "adventure-doll-house",
    blurb: "Three-storey doll house with furniture set.",
    categorySlug: "pretend",
    collections: ["featured"],
    skuPrefix: "LP-DOLL",
    variants: [{ suffix: "3S", title: "3-storey", price: 4999, compareAt: 5999, qty: stock(20) }],
  }),
  product({
    title: "ZoomRace Track Set",
    handle: "zoomrace-track-set",
    blurb: "Flexible race track with 2 cars and loops.",
    categorySlug: "vehicles",
    collections: ["bestsellers"],
    skuPrefix: "LP-RACE",
    variants: [{ suffix: "SET", title: "Track + 2 cars", price: 2499, qty: stock(35) }],
  }),
  product({
    title: "SoftBuddy Plush Bear",
    handle: "softbuddy-plush-bear",
    blurb: "Hypoallergenic plush bear, machine washable.",
    categorySlug: "plush",
    skuPrefix: "LP-PLUSH",
    variants: [
      { suffix: "SM", title: "Small 25cm", price: 799, qty: stock(100) },
      { suffix: "LG", title: "Large 45cm", price: 1499, qty: stock(60) },
    ],
  }),
  product({
    title: "STEM Robot Kit Junior",
    handle: "stem-robot-kit-junior",
    blurb: "Build-and-code robot kit for ages 8+.",
    categorySlug: "stem",
    collections: ["new-arrivals", "featured"],
    skuPrefix: "LP-ROBO",
    variants: [{ suffix: "JR", title: "Junior kit", price: 3499, compareAt: 3999, qty: stock(40) }],
  }),
  product({
    title: "SplashFun Bath Set",
    handle: "splashfun-bath-set",
    blurb: "Floating bath toys with cup and duck trio.",
    categorySlug: "preschool",
    skuPrefix: "LP-BATH",
    variants: [{ suffix: "SET", title: "Set", price: 599, qty: stock(85) }],
  }),
  product({
    title: "PuzzleMap India 100pc",
    handle: "puzzlemap-india-100",
    blurb: "Floor puzzle of Indian states and capitals.",
    categorySlug: "puzzles",
    collections: ["bestsellers"],
    skuPrefix: "LP-PUZ",
    variants: [{ suffix: "100", title: "100 pieces", price: 899, qty: stock(55) }],
  }),
  product({
    title: "MelodyXylophone Kids",
    handle: "melody-xylophone",
    blurb: "Colourful 8-note xylophone with mallets.",
    categorySlug: "music",
    skuPrefix: "LP-XYL",
    variants: [{ suffix: "8N", title: "8-note", price: 749, qty: stock(70) }],
  }),
  product({
    title: "OutdoorCatch Ball Set",
    handle: "outdoorcatch-ball",
    blurb: "Soft foam ball set for backyard play.",
    categorySlug: "outdoor",
    skuPrefix: "LP-BALL",
    variants: [{ suffix: "3PK", title: "3-pack", price: 499, qty: stock(110) }],
  }),
  product({
    title: "KitchenPlay Mini Set",
    handle: "kitchenplay-mini",
    blurb: "Pretend kitchen utensils and food set.",
    categorySlug: "pretend",
    collections: ["new-arrivals"],
    skuPrefix: "LP-KIT",
    variants: [{ suffix: "MINI", title: "Mini set", price: 1299, qty: stock(45) }],
  }),
  product({
    title: "GlowStick Art Board",
    handle: "glowstick-art-board",
    blurb: "LED drawing board with stencil sheets.",
    categorySlug: "arts",
    skuPrefix: "LP-ART",
    variants: [{ suffix: "LED", title: "LED board", price: 999, qty: stock(65) }],
  }),
  product({
    title: "TinyTown Fire Truck",
    handle: "tinytown-fire-truck",
    blurb: "Die-cast fire truck with lights and sound.",
    categorySlug: "vehicles",
    skuPrefix: "LP-FIRE",
    variants: [{ suffix: "DC", title: "Die-cast", price: 1199, qty: stock(50) }],
  }),
  product({
    title: "StoryTime Picture Cards",
    handle: "storytime-picture-cards",
    blurb: "36 illustrated cards for storytelling games.",
    categorySlug: "learning",
    collections: ["featured"],
    skuPrefix: "LP-CARD",
    variants: [{ suffix: "36", title: "36 cards", price: 549, qty: stock(80) }],
  }),
  product({
    title: "BalanceBike 12 Inch",
    handle: "balancebike-12",
    blurb: "Wooden balance bike for ages 2–5.",
    categorySlug: "outdoor",
    collections: ["bestsellers"],
    skuPrefix: "LP-BIKE",
    variants: [
      { suffix: "NAT", title: "Natural wood", price: 3999, qty: stock(25) },
      { suffix: "RED", title: "Red", price: 3999, qty: stock(22) },
    ],
  }),
  product({
    title: "ClayCraft Modeling Kit",
    handle: "claycraft-modeling",
    blurb: "Non-toxic modeling clay with tools and molds.",
    categorySlug: "arts",
    skuPrefix: "LP-CLAY",
    variants: [{ suffix: "KIT", title: "Kit", price: 649, qty: stock(75) }],
  }),
  product({
    title: "SpaceExplorer Telescope Toy",
    handle: "spaceexplorer-telescope",
    blurb: "Kids telescope with star chart booklet.",
    categorySlug: "stem",
    collections: ["new-arrivals"],
    skuPrefix: "LP-TEL",
    variants: [{ suffix: "JR", title: "Junior", price: 1799, qty: stock(30) }],
  }),
  product({
    title: "FamilyBoard Ludo Deluxe",
    handle: "familyboard-ludo-deluxe",
    blurb: "Wooden Ludo set with dice and tokens.",
    categorySlug: "games",
    skuPrefix: "LP-LUDO",
    variants: [{ suffix: "WD", title: "Wooden", price: 899, qty: stock(60) }],
  }),
  product({
    title: "BabyGym Activity Playmat",
    handle: "babygym-playmat",
    blurb: "Tummy-time playmat with hanging toys.",
    categorySlug: "preschool",
    collections: ["featured"],
    skuPrefix: "LP-GYM",
    variants: [{ suffix: "MAT", title: "Playmat", price: 2299, compareAt: 2699, qty: stock(35) }],
  }),
  product({
    title: "MagicSand Kinetic 1kg",
    handle: "magicsand-kinetic-1kg",
    blurb: "Kinetic sand tub with molds, 1 kg.",
    categorySlug: "arts",
    skuPrefix: "LP-SAND",
    variants: [{ suffix: "1KG", title: "1 kg", price: 799, qty: stock(70) }],
  }),
  product({
    title: "JuniorDoctor Roleplay Kit",
    handle: "juniordoctor-kit",
    blurb: "Doctor roleplay kit with stethoscope and case.",
    categorySlug: "pretend",
    skuPrefix: "LP-DOC",
    variants: [{ suffix: "KIT", title: "Kit", price: 1099, qty: stock(48) }],
  }),
];

function customersFor(slug: string, city: string, state: string, pin: string) {
  return [
    {
      email: `priya.${slug}@example.com`,
      name: "Priya Sharma",
      phone: "+919811100001",
      address: {
        name: "Priya Sharma",
        phone: "+919811100001",
        addressLine1: "12 MG Road",
        addressLine2: "Near City Mall",
        city,
        state,
        postalCode: pin,
      },
    },
    {
      email: `arjun.${slug}@example.com`,
      name: "Arjun Mehta",
      phone: "+919811100002",
      address: {
        name: "Arjun Mehta",
        phone: "+919811100002",
        addressLine1: "45 Lake View Apartments",
        city,
        state,
        postalCode: pin,
      },
    },
    {
      email: `neha.${slug}@example.com`,
      name: "Neha Kapoor",
      phone: "+919811100003",
      address: {
        name: "Neha Kapoor",
        phone: "+919811100003",
        addressLine1: "88 Residency Road",
        city,
        state,
        postalCode: pin,
      },
    },
  ];
}

export const DEMO_STORES: readonly DemoStoreSeed[] = [
  {
    name: "TechNova",
    slug: "technova",
    adminEmail: "admin@technova.local",
    orderPrefix: "TN",
    settings: {
      currency: "INR",
      timezone: "Asia/Kolkata",
      shipping: { mode: "flat", flatPaise: 20_000, freeOverPaise: null },
      tax: { gstPercent: 18, gstin: "29AABCT1332L1ZV" },
    },
    categories: [
      { name: "Electronics", slug: "electronics" },
      { name: "Audio", slug: "audio", parentSlug: "electronics" },
      { name: "Wearables", slug: "wearables", parentSlug: "electronics" },
      { name: "Computers", slug: "computers", parentSlug: "electronics" },
      { name: "Accessories", slug: "accessories", parentSlug: "electronics" },
      { name: "Power", slug: "power", parentSlug: "electronics" },
      { name: "Networking", slug: "networking", parentSlug: "electronics" },
      { name: "Smart Home", slug: "smart-home", parentSlug: "electronics" },
      { name: "Storage", slug: "storage", parentSlug: "electronics" },
    ],
    collections: [
      { name: "Featured", slug: "featured", description: "Editor picks from TechNova" },
      { name: "New Arrivals", slug: "new-arrivals", description: "Latest gadgets" },
    ],
    products: technovaProducts,
    customers: customersFor("technova", "Bengaluru", "Karnataka", "560001"),
    discounts: [
      { code: "NOVA10", type: "PERCENTAGE", value: 10, minOrderPaise: inr(1000), usageLimit: 500 },
      { code: "TECH200", type: "FIXED_PAISE", value: inr(200), minOrderPaise: inr(2000) },
    ],
    cart: {
      customerEmail: "priya.technova@example.com",
      items: [
        { sku: "TN-EAR-BLK", quantity: 1 },
        { sku: "TN-CBL-6PK", quantity: 2 },
      ],
    },
    orders: [
      {
        orderNumber: "TN-1001",
        customerEmail: "arjun.technova@example.com",
        status: "DELIVERED",
        discountCode: "NOVA10",
        items: [
          { productHandle: "pulsewatch-x", sku: "TN-WATCH-42-BLK", quantity: 1 },
          { productHandle: "cablekit-pro", sku: "TN-CBL-6PK", quantity: 1 },
        ],
      },
      {
        orderNumber: "TN-1002",
        customerEmail: "neha.technova@example.com",
        status: "SHIPPED",
        items: [{ productHandle: "novabuds-pro", sku: "TN-EAR-WHT", quantity: 1 }],
      },
      {
        orderNumber: "TN-1003",
        customerEmail: "priya.technova@example.com",
        status: "CONFIRMED",
        discountCode: "TECH200",
        items: [
          { productHandle: "typefast-mech-keyboard", sku: "TN-KB-RED", quantity: 1 },
          { productHandle: "precision-pro-mouse", sku: "TN-MSE-BLK", quantity: 1 },
        ],
      },
    ],
  },
  {
    name: "UrbanThread",
    slug: "urbanthread",
    adminEmail: "admin@urbanthread.local",
    orderPrefix: "UT",
    settings: {
      currency: "INR",
      timezone: "Asia/Kolkata",
      shipping: { mode: "free_over", flatPaise: 15_000, freeOverPaise: 200_000 },
      tax: { gstPercent: 5, gstin: "27AABCU9603R1ZM" },
    },
    categories: [
      { name: "Apparel", slug: "apparel" },
      { name: "Shirts", slug: "shirts", parentSlug: "apparel" },
      { name: "Tees", slug: "tees", parentSlug: "apparel" },
      { name: "Bottoms", slug: "bottoms", parentSlug: "apparel" },
      { name: "Outerwear", slug: "outerwear", parentSlug: "apparel" },
      { name: "Dresses", slug: "dresses", parentSlug: "apparel" },
      { name: "Ethnic", slug: "ethnic", parentSlug: "apparel" },
      { name: "Activewear", slug: "activewear", parentSlug: "apparel" },
      { name: "Loungewear", slug: "loungewear", parentSlug: "apparel" },
      { name: "Footwear", slug: "footwear", parentSlug: "apparel" },
      { name: "Accessories", slug: "accessories", parentSlug: "apparel" },
    ],
    collections: [
      { name: "Featured", slug: "featured", description: "Season highlights" },
      { name: "Bestsellers", slug: "bestsellers", description: "Customer favourites" },
      { name: "New Arrivals", slug: "new-arrivals", description: "Just dropped" },
    ],
    products: urbanThreadProducts,
    customers: customersFor("urbanthread", "Mumbai", "Maharashtra", "400001"),
    discounts: [
      { code: "STYLE15", type: "PERCENTAGE", value: 15, minOrderPaise: inr(1500) },
      { code: "URBAN100", type: "FIXED_PAISE", value: inr(100), minOrderPaise: inr(999) },
    ],
    cart: {
      customerEmail: "neha.urbanthread@example.com",
      items: [
        { sku: "UT-TEE-M-WHT", quantity: 2 },
        { sku: "UT-CHINO-32-BGE", quantity: 1 },
      ],
    },
    orders: [
      {
        orderNumber: "UT-2001",
        customerEmail: "priya.urbanthread@example.com",
        status: "DELIVERED",
        discountCode: "STYLE15",
        items: [
          { productHandle: "cityline-oxford-shirt", sku: "UT-SHIRT-M-WHT", quantity: 1 },
          { productHandle: "metro-slim-chinos", sku: "UT-CHINO-34-NVY", quantity: 1 },
        ],
      },
      {
        orderNumber: "UT-2002",
        customerEmail: "arjun.urbanthread@example.com",
        status: "PROCESSING",
        items: [{ productHandle: "aether-soft-hoodie", sku: "UT-HOOD-L-BLK", quantity: 1 }],
      },
    ],
  },
  {
    name: "FitZone",
    slug: "fitzone",
    adminEmail: "admin@fitzone.local",
    orderPrefix: "FZ",
    settings: {
      currency: "INR",
      timezone: "Asia/Kolkata",
      shipping: { mode: "flat", flatPaise: 25_000, freeOverPaise: null },
      tax: { gstPercent: 12, gstin: "07AABCF1234A1Z5" },
    },
    categories: [
      { name: "Fitness", slug: "fitness" },
      { name: "Strength", slug: "strength", parentSlug: "fitness" },
      { name: "Cardio", slug: "cardio", parentSlug: "fitness" },
      { name: "Yoga", slug: "yoga", parentSlug: "fitness" },
      { name: "Recovery", slug: "recovery", parentSlug: "fitness" },
      { name: "Footwear", slug: "footwear", parentSlug: "fitness" },
      { name: "Apparel", slug: "apparel", parentSlug: "fitness" },
      { name: "Wearables", slug: "wearables", parentSlug: "fitness" },
      { name: "Aquatic", slug: "aquatic", parentSlug: "fitness" },
      { name: "Accessories", slug: "accessories", parentSlug: "fitness" },
    ],
    collections: [
      { name: "Featured", slug: "featured", description: "Train harder" },
      { name: "Bestsellers", slug: "bestsellers", description: "Gym favourites" },
      { name: "New Arrivals", slug: "new-arrivals", description: "Fresh gear" },
    ],
    products: fitZoneProducts,
    customers: customersFor("fitzone", "Delhi", "Delhi", "110001"),
    discounts: [
      { code: "FIT20", type: "PERCENTAGE", value: 20, minOrderPaise: inr(2000), usageLimit: 200 },
      { code: "ZONE150", type: "FIXED_PAISE", value: inr(150) },
    ],
    cart: {
      customerEmail: "arjun.fitzone@example.com",
      items: [
        { sku: "FZ-BAND-5PK", quantity: 1 },
        { sku: "FZ-MAT-TEAL", quantity: 1 },
      ],
    },
    orders: [
      {
        orderNumber: "FZ-3001",
        customerEmail: "priya.fitzone@example.com",
        status: "SHIPPED",
        discountCode: "FIT20",
        items: [
          { productHandle: "pacepro-running-shoes", sku: "FZ-RUN-8-BLU", quantity: 1 },
          { productHandle: "hydrofuel-bottle-1l", sku: "FZ-BTL-BLK", quantity: 1 },
        ],
      },
      {
        orderNumber: "FZ-3002",
        customerEmail: "neha.fitzone@example.com",
        status: "CONFIRMED",
        items: [{ productHandle: "irongrip-adjustable-dumbbells", sku: "FZ-DB-24KG", quantity: 1 }],
      },
    ],
  },
  {
    name: "BookNest",
    slug: "booknest",
    adminEmail: "admin@booknest.local",
    orderPrefix: "BN",
    settings: {
      currency: "INR",
      timezone: "Asia/Kolkata",
      shipping: { mode: "free_over", flatPaise: 10_000, freeOverPaise: 99_900 },
      tax: { gstPercent: 0, gstin: null },
    },
    categories: [
      { name: "Books & Stationery", slug: "books-stationery" },
      { name: "Fiction", slug: "fiction", parentSlug: "books-stationery" },
      { name: "Non-Fiction", slug: "non-fiction", parentSlug: "books-stationery" },
      { name: "Children", slug: "children", parentSlug: "books-stationery" },
      { name: "Business", slug: "business", parentSlug: "books-stationery" },
      { name: "Education", slug: "education", parentSlug: "books-stationery" },
      { name: "Wellness", slug: "wellness", parentSlug: "books-stationery" },
      { name: "Stationery", slug: "stationery", parentSlug: "books-stationery" },
      { name: "Accessories", slug: "accessories", parentSlug: "books-stationery" },
    ],
    collections: [
      { name: "Featured", slug: "featured", description: "Staff picks" },
      { name: "Bestsellers", slug: "bestsellers", description: "Top sellers" },
      { name: "New Arrivals", slug: "new-arrivals", description: "Fresh on the shelf" },
    ],
    products: bookNestProducts,
    customers: customersFor("booknest", "Pune", "Maharashtra", "411001"),
    discounts: [
      { code: "READ10", type: "PERCENTAGE", value: 10, minOrderPaise: inr(500) },
      { code: "NEST50", type: "FIXED_PAISE", value: inr(50), minOrderPaise: inr(300) },
    ],
    cart: {
      customerEmail: "priya.booknest@example.com",
      items: [
        { sku: "BN-FIC-PB", quantity: 1 },
        { sku: "BN-NB-A5-NVY", quantity: 2 },
      ],
    },
    orders: [
      {
        orderNumber: "BN-4001",
        customerEmail: "arjun.booknest@example.com",
        status: "DELIVERED",
        discountCode: "READ10",
        items: [
          { productHandle: "startup-finance-playbook", sku: "BN-BIZ-PB", quantity: 1 },
          { productHandle: "inkwell-fountain-set", sku: "BN-PEN-SET", quantity: 1 },
        ],
      },
      {
        orderNumber: "BN-4002",
        customerEmail: "neha.booknest@example.com",
        status: "CONFIRMED",
        items: [{ productHandle: "atlas-indian-birds", sku: "BN-NF-HC", quantity: 1 }],
      },
    ],
  },
  {
    name: "LittlePlay",
    slug: "littleplay",
    adminEmail: "admin@littleplay.local",
    orderPrefix: "LP",
    settings: {
      currency: "INR",
      timezone: "Asia/Kolkata",
      shipping: { mode: "flat", flatPaise: 18_000, freeOverPaise: null },
      tax: { gstPercent: 12, gstin: "33AABCL5678B1Z9" },
    },
    categories: [
      { name: "Toys", slug: "toys" },
      { name: "Building", slug: "building", parentSlug: "toys" },
      { name: "Preschool", slug: "preschool", parentSlug: "toys" },
      { name: "Pretend", slug: "pretend", parentSlug: "toys" },
      { name: "Vehicles", slug: "vehicles", parentSlug: "toys" },
      { name: "Plush", slug: "plush", parentSlug: "toys" },
      { name: "STEM", slug: "stem", parentSlug: "toys" },
      { name: "Puzzles", slug: "puzzles", parentSlug: "toys" },
      { name: "Music", slug: "music", parentSlug: "toys" },
      { name: "Outdoor", slug: "outdoor", parentSlug: "toys" },
      { name: "Arts", slug: "arts", parentSlug: "toys" },
      { name: "Learning", slug: "learning", parentSlug: "toys" },
      { name: "Games", slug: "games", parentSlug: "toys" },
    ],
    collections: [
      { name: "Featured", slug: "featured", description: "Play favourites" },
      { name: "Bestsellers", slug: "bestsellers", description: "Kids love these" },
      { name: "New Arrivals", slug: "new-arrivals", description: "Just unboxed" },
    ],
    products: littlePlayProducts,
    customers: customersFor("littleplay", "Hyderabad", "Telangana", "500001"),
    discounts: [
      { code: "PLAY15", type: "PERCENTAGE", value: 15, minOrderPaise: inr(1000) },
      { code: "KIDS100", type: "FIXED_PAISE", value: inr(100), minOrderPaise: inr(799) },
    ],
    cart: {
      customerEmail: "neha.littleplay@example.com",
      items: [
        { sku: "LP-PLUSH-SM", quantity: 1 },
        { sku: "LP-PUZ-100", quantity: 1 },
      ],
    },
    orders: [
      {
        orderNumber: "LP-5001",
        customerEmail: "priya.littleplay@example.com",
        status: "DELIVERED",
        discountCode: "PLAY15",
        items: [
          { productHandle: "buildbox-wooden-blocks", sku: "LP-BLK-50", quantity: 1 },
          { productHandle: "softbuddy-plush-bear", sku: "LP-PLUSH-LG", quantity: 1 },
        ],
      },
      {
        orderNumber: "LP-5002",
        customerEmail: "arjun.littleplay@example.com",
        status: "SHIPPED",
        items: [{ productHandle: "stem-robot-kit-junior", sku: "LP-ROBO-JR", quantity: 1 }],
      },
      {
        orderNumber: "LP-5003",
        customerEmail: "neha.littleplay@example.com",
        status: "CONFIRMED",
        discountCode: "KIDS100",
        items: [
          { productHandle: "zoomrace-track-set", sku: "LP-RACE-SET", quantity: 1 },
          { productHandle: "melody-xylophone", sku: "LP-XYL-8N", quantity: 1 },
        ],
      },
    ],
  },
];

// Sanity: each demo catalog must have at least 20 products.
for (const store of DEMO_STORES) {
  if (store.products.length < 20) {
    throw new Error(`Demo store ${store.slug} has only ${store.products.length} products; need ≥20.`);
  }
}
