/** Platform Global Catalog seed: 6×10 products with 2 product-matched image prompts each. */

export const GLOBAL_CATALOG_SEED_VERSION = "v3-exact-match-120png";

export type GlobalCatalogSeedProduct = {
  title: string;
  handle: string;
  shortDescription: string;
  description: string;
  sku: string;
  variantTitle: string;
  pricePaise: number;
  /** Local filenames under seed-data/global-catalog-media/ */
  imageFiles: readonly [string, string];
  /** Photorealistic prompts for front and alternate views of THIS exact product. */
  imagePrompts: readonly [string, string];
};

export type GlobalCatalogSeedCategory = {
  name: string;
  slug: string;
  products: readonly GlobalCatalogSeedProduct[];
};

export const GLOBAL_CATALOG_SEED: readonly GlobalCatalogSeedCategory[] = [
  {
    name: 'Beauty Products',
    slug: 'beauty-products',
    products: [
      {
        title: 'Lakmé Absolute Matte Lipstick Ruby Rush',
        handle: 'lakme-absolute-matte-lipstick-ruby-rush',
        shortDescription: 'Long-wear matte lipstick in a deep ruby shade.',
        description: 'Velvety matte lipstick with intense colour payoff and a comfortable non-drying formula. Ideal for everyday and festive looks. Made for Indian skin tones.',
        sku: 'GC-BEAU-LIP-001',
        variantTitle: 'Ruby Rush 3.7g',
        pricePaise: 69900,
        imageFiles: ['lakme-absolute-matte-lipstick-ruby-rush-front.png', 'lakme-absolute-matte-lipstick-ruby-rush-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a slim gold-capped lipstick tube with deep ruby-red matte bullet extended, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of closed gold lipstick tube standing upright next to the same ruby-red bullet lying beside it, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Mamaearth Vitamin C Face Wash',
        handle: 'mamaearth-vitamin-c-face-wash',
        shortDescription: 'Brightening face wash with vitamin C and turmeric.',
        description: 'Gentle daily cleanser that helps fade dullness while keeping skin soft. Free from harsh sulphates. Suitable for all skin types.',
        sku: 'GC-BEAU-FW-002',
        variantTitle: '100 ml',
        pricePaise: 24900,
        imageFiles: ['mamaearth-vitamin-c-face-wash-front.png', 'mamaearth-vitamin-c-face-wash-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of an orange translucent plastic face wash squeeze bottle with white pump on white background, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same orange face wash bottle from a low side angle showing the pump and label area, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'The Ordinary Niacinamide 10% + Zinc 1%',
        handle: 'ordinary-niacinamide-zinc-serum',
        shortDescription: 'Oil-control serum for clearer-looking skin.',
        description: 'Water-based serum that targets visible blemishes and excess sebum. Lightweight texture absorbs quickly under moisturiser.',
        sku: 'GC-BEAU-SER-003',
        variantTitle: '30 ml',
        pricePaise: 89000,
        imageFiles: ['ordinary-niacinamide-zinc-serum-front.png', 'ordinary-niacinamide-zinc-serum-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a clear glass dropper bottle of niacinamide facial serum with white dropper cap and minimal clinical label, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same clear serum dropper bottle angled to show the dropper pipette and liquid, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Maybelline Fit Me Foundation Ivory',
        handle: 'maybelline-fit-me-foundation-ivory',
        shortDescription: 'Natural matte foundation with buildable coverage.',
        description: 'Oil-free liquid foundation that blurs pores for a natural finish. Matches fair-to-light Indian undertones.',
        sku: 'GC-BEAU-FDN-004',
        variantTitle: 'Ivory 128 30ml',
        pricePaise: 54900,
        imageFiles: ['maybelline-fit-me-foundation-ivory-front.png', 'maybelline-fit-me-foundation-ivory-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a glass liquid foundation bottle with pump, ivory beige foundation visible inside, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same ivory foundation bottle from the back three-quarter angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Biotique Bio Coconut Whitening Cream',
        handle: 'biotique-bio-coconut-cream',
        shortDescription: 'Ayurvedic day cream with coconut extracts.',
        description: 'Lightweight cream that hydrates and brightens for a healthy glow. Non-greasy formula for humid Indian weather.',
        sku: 'GC-BEAU-CRM-005',
        variantTitle: '50 g',
        pricePaise: 19900,
        imageFiles: ['biotique-bio-coconut-cream-front.png', 'biotique-bio-coconut-cream-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a round white cream jar of coconut face cream with green herbal accents on the lid, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same coconut cream jar open with lid beside it showing white cream texture, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Nykaa Naturals Kajal Black',
        handle: 'nykaa-naturals-kajal-black',
        shortDescription: 'Smudge-proof natural kajal for all-day wear.',
        description: 'Intense black kajal with plant oils for smooth glide. Dermatologically tested and suitable for sensitive eyes.',
        sku: 'GC-BEAU-KJL-006',
        variantTitle: 'Black 2.5g',
        pricePaise: 29900,
        imageFiles: ['nykaa-naturals-kajal-black-front.png', 'nykaa-naturals-kajal-black-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a black kajal eyeliner pencil with sharpened tip showing deep black pigment, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black kajal pencil with cap off lying diagonally showing full length, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Plum Green Tea Night Gel',
        handle: 'plum-green-tea-night-gel',
        shortDescription: 'Oil-free night gel for combination skin.',
        description: 'Refreshing overnight gel with green tea that calms and balances overnight oiliness without clogging pores.',
        sku: 'GC-BEAU-NGT-007',
        variantTitle: '50 ml',
        pricePaise: 47500,
        imageFiles: ['plum-green-tea-night-gel-front.png', 'plum-green-tea-night-gel-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a clear jar of light green tea night gel cream with purple accents, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same green tea night gel jar from side view with lid closed, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Minimalist 2% Alpha Arbutin Serum',
        handle: 'minimalist-alpha-arbutin-serum',
        shortDescription: 'Hyperpigmentation serum with alpha arbutin.',
        description: 'Targets dark spots and uneven tone. Fragrance-free and suitable for daily AM/PM use under sunscreen.',
        sku: 'GC-BEAU-ABT-008',
        variantTitle: '30 ml',
        pricePaise: 54900,
        imageFiles: ['minimalist-alpha-arbutin-serum-front.png', 'minimalist-alpha-arbutin-serum-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a frosted white dropper bottle of alpha arbutin brightening serum, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same frosted serum bottle angled with dropper slightly lifted, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Dot & Key Strawberry Dew Sunscreen SPF 50',
        handle: 'dot-key-strawberry-sunscreen-spf50',
        shortDescription: 'Lightweight gel sunscreen with SPF 50 PA+++.',
        description: 'Non-whitening gel sunscreen that leaves a dewy finish. Broad-spectrum protection for daily urban wear.',
        sku: 'GC-BEAU-SUN-009',
        variantTitle: '50 g',
        pricePaise: 49500,
        imageFiles: ['dot-key-strawberry-sunscreen-spf50-front.png', 'dot-key-strawberry-sunscreen-spf50-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a pink squeeze tube of strawberry gel sunscreen standing upright, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same pink sunscreen tube lying flat showing the nozzle and body, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Sugar Cosmetics Contour De Force Blush',
        handle: 'sugar-contour-de-force-blush',
        shortDescription: 'Buildable powder blush for a natural flush.',
        description: 'Finely milled blush that blends easily and lasts through the day. Perfect for soft daytime makeup.',
        sku: 'GC-BEAU-BLS-010',
        variantTitle: 'Peach Peak 4g',
        pricePaise: 59900,
        imageFiles: ['sugar-contour-de-force-blush-front.png', 'sugar-contour-de-force-blush-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of an open round peach powder blush compact with mirror and soft peach powder pan, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same blush compact closed showing the top lid design, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
    ],
  },
  {
    name: 'Shoes',
    slug: 'shoes',
    products: [
      {
        title: 'Nike Revolution 7 Running Shoes',
        handle: 'nike-revolution-7-running-shoes',
        shortDescription: 'Breathable mesh runners for daily training.',
        description: 'Lightweight running shoes with soft foam cushioning and a secure lace-up fit. Built for road runs and gym warm-ups.',
        sku: 'GC-SHOE-NK-001',
        variantTitle: 'UK 8 / Men',
        pricePaise: 449900,
        imageFiles: ['nike-revolution-7-running-shoes-front.png', 'nike-revolution-7-running-shoes-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a pair of black and grey mesh running shoes with white midsole, three-quarter front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black grey running shoes side profile view showing sole and heel counter, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Adidas Breaknet Court Sneakers',
        handle: 'adidas-breaknet-court-sneakers',
        shortDescription: 'Classic court-inspired everyday sneakers.',
        description: 'Clean leather-look uppers with rubber outsole grip. Pairs easily with jeans and athleisure.',
        sku: 'GC-SHOE-AD-002',
        variantTitle: 'UK 9 / Men',
        pricePaise: 399900,
        imageFiles: ['adidas-breaknet-court-sneakers-front.png', 'adidas-breaknet-court-sneakers-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of white leather court sneakers with navy accents and rubber cupsole, angled front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same white court sneakers from the outer side profile, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Puma Smash Vulc Canvas Shoes',
        handle: 'puma-smash-vulc-canvas',
        shortDescription: 'Casual canvas sneakers with vulcanised sole.',
        description: 'Durable canvas upper and flexible vulcanised outsole for all-day comfort around campus and city walks.',
        sku: 'GC-SHOE-PM-003',
        variantTitle: 'UK 7 / Unisex',
        pricePaise: 279900,
        imageFiles: ['puma-smash-vulc-canvas-front.png', 'puma-smash-vulc-canvas-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of navy blue canvas low-top sneakers with white vulcanized sole, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same navy canvas sneakers rear three-quarter view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Bata Comfit Formal Oxfords',
        handle: 'bata-comfit-formal-oxfords',
        shortDescription: 'Office-ready leatherette oxfords with cushioned insoles.',
        description: 'Smart lace-up oxfords designed for long office hours. Soft lining and slip-resistant sole.',
        sku: 'GC-SHOE-BT-004',
        variantTitle: 'UK 8 / Men',
        pricePaise: 189900,
        imageFiles: ['bata-comfit-formal-oxfords-front.png', 'bata-comfit-formal-oxfords-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of polished brown formal oxford lace-up dress shoes, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same brown oxford shoes side view showing heel and lace eyelets, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Skechers Go Walk Arch Fit',
        handle: 'skechers-go-walk-arch-fit',
        shortDescription: 'Walking shoes with arch-support footbed.',
        description: 'Machine-washable uppers and responsive cushioning for daily walks and travel days.',
        sku: 'GC-SHOE-SK-005',
        variantTitle: 'UK 6 / Women',
        pricePaise: 549900,
        imageFiles: ['skechers-go-walk-arch-fit-front.png', 'skechers-go-walk-arch-fit-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of light grey slip-on walking shoes with thick white foam sole, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same grey walking shoes side view highlighting arch support sole, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Crocs Classic Clog',
        handle: 'crocs-classic-clog',
        shortDescription: 'Iconic lightweight clogs for casual wear.',
        description: 'Easy-on clog with ventilation ports and pivoting heel strap. Ideal for monsoon and indoor comfort.',
        sku: 'GC-SHOE-CR-006',
        variantTitle: 'UK 8 / Unisex',
        pricePaise: 299900,
        imageFiles: ['crocs-classic-clog-front.png', 'crocs-classic-clog-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of iconic seafoam green foam clogs with ventilation holes and heel strap, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same green foam clogs from the back showing pivoting heel strap, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Red Tape Casual Loafers',
        handle: 'red-tape-casual-loafers',
        shortDescription: 'Slip-on loafers in premium synthetic leather.',
        description: 'Smart-casual loafers with padded footbed. Great for college and smart weekend outfits.',
        sku: 'GC-SHOE-RT-007',
        variantTitle: 'UK 9 / Men',
        pricePaise: 219900,
        imageFiles: ['red-tape-casual-loafers-front.png', 'red-tape-casual-loafers-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of tan synthetic leather slip-on loafers with stitching detail, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same tan loafers side profile view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Campus OG-06 Sports Shoes',
        handle: 'campus-og-06-sports-shoes',
        shortDescription: 'Affordable mesh sports shoes for training.',
        description: 'Breathable mesh, lace closure, and cushioned midsole for school sports and light jogging.',
        sku: 'GC-SHOE-CP-008',
        variantTitle: 'UK 7 / Men',
        pricePaise: 129900,
        imageFiles: ['campus-og-06-sports-shoes-front.png', 'campus-og-06-sports-shoes-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of blue and white mesh sports trainers with lace-up closure, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same blue white sports trainers outer side view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Woodland Leather Trekking Sandals',
        handle: 'woodland-leather-trekking-sandals',
        shortDescription: 'Rugged outdoor sandals with adjustable straps.',
        description: 'Durable leather straps and grippy outsole for hills and monsoon trails.',
        sku: 'GC-SHOE-WL-009',
        variantTitle: 'UK 8 / Men',
        pricePaise: 349900,
        imageFiles: ['woodland-leather-trekking-sandals-front.png', 'woodland-leather-trekking-sandals-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of rugged brown leather trekking sandals with adjustable buckles, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same brown trekking sandals sole-up angled view showing tread, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Metro Women Block Heels',
        handle: 'metro-women-block-heels',
        shortDescription: 'Comfort block heels for festive occasions.',
        description: 'Stable block heel with cushioned sole and elegant finish for weddings and parties.',
        sku: 'GC-SHOE-MT-010',
        variantTitle: 'UK 5 / Women',
        pricePaise: 169900,
        imageFiles: ['metro-women-block-heels-front.png', 'metro-women-block-heels-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of elegant nude beige women block heel pumps, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same nude block heel pumps side profile showing heel height, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
    ],
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    products: [
      {
        title: 'boAt Airdopes 141 TWS Earbuds',
        handle: 'boat-airdopes-141-tws',
        shortDescription: 'True wireless earbuds with 42-hour playback.',
        description: 'Immersive sound, IPX4 sweat resistance, and a compact charging case. Ideal for commute and workouts.',
        sku: 'GC-ELEC-BT-001',
        variantTitle: 'Black',
        pricePaise: 129900,
        imageFiles: ['boat-airdopes-141-tws-front.png', 'boat-airdopes-141-tws-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of matte black true wireless earbuds resting in an open black charging case, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black TWS earbuds and case closed from a side angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Noise ColorFit Pro 5 Smartwatch',
        handle: 'noise-colorfit-pro-5',
        shortDescription: '1.85" AMOLED smartwatch with Bluetooth calling.',
        description: 'Track heart rate, SpO2, and sleep. 7-day battery and 100+ sports modes for Indian fitness routines.',
        sku: 'GC-ELEC-NW-002',
        variantTitle: 'Chase Black',
        pricePaise: 499900,
        imageFiles: ['noise-colorfit-pro-5-front.png', 'noise-colorfit-pro-5-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a black square AMOLED smartwatch with sport strap displaying a fitness watch face, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black smartwatch side profile showing thickness and buttons, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'JBL Go 3 Portable Bluetooth Speaker',
        handle: 'jbl-go-3-bluetooth-speaker',
        shortDescription: 'Ultra-portable waterproof Bluetooth speaker.',
        description: 'Bold JBL sound in a pocket-friendly body with IP67 rating for poolside and travel use.',
        sku: 'GC-ELEC-JBL-003',
        variantTitle: 'Blue',
        pricePaise: 399900,
        imageFiles: ['jbl-go-3-bluetooth-speaker-front.png', 'jbl-go-3-bluetooth-speaker-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a compact blue portable Bluetooth speaker with fabric grille and loop, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same blue portable speaker from the back showing ports and clip, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Mi 10000mAh Power Bank 3i',
        handle: 'mi-10000mah-power-bank-3i',
        shortDescription: 'Dual-output power bank with 18W fast charge.',
        description: 'Slim aluminium body with two USB-A ports to charge phones and accessories on the go.',
        sku: 'GC-ELEC-MI-004',
        variantTitle: 'Black 10000mAh',
        pricePaise: 129900,
        imageFiles: ['mi-10000mah-power-bank-3i-front.png', 'mi-10000mah-power-bank-3i-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a slim black aluminium 10000mAh power bank brick, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black power bank showing dual USB ports on the end, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Logitech M331 Silent Wireless Mouse',
        handle: 'logitech-m331-silent-mouse',
        shortDescription: 'Silent-click wireless mouse for office work.',
        description: '2.4 GHz nano receiver, 24-month battery life, and quiet clicks for shared workspaces.',
        sku: 'GC-ELEC-LG-005',
        variantTitle: 'Black',
        pricePaise: 149900,
        imageFiles: ['logitech-m331-silent-mouse-front.png', 'logitech-m331-silent-mouse-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a black ergonomic wireless office mouse, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black wireless mouse underside showing sensor and battery cover, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'SanDisk Ultra 128GB USB 3.0 Pendrive',
        handle: 'sandisk-ultra-128gb-usb3',
        shortDescription: 'High-speed USB 3.0 flash drive.',
        description: 'Transfer HD videos and documents quickly. Retractable design with up to 100 MB/s read speed.',
        sku: 'GC-ELEC-SD-006',
        variantTitle: '128 GB',
        pricePaise: 89900,
        imageFiles: ['sandisk-ultra-128gb-usb3-front.png', 'sandisk-ultra-128gb-usb3-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a red and silver retractable USB 3.0 flash drive with connector extended, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same USB pendrive with connector retracted, side view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Amazon Basics HDMI Cable 2m',
        handle: 'amazon-basics-hdmi-2m',
        shortDescription: 'High-speed HDMI cable for 4K displays.',
        description: 'Connect laptops, TV sticks, and consoles with stable 4K@60Hz signal over 2 metres.',
        sku: 'GC-ELEC-HDMI-007',
        variantTitle: '2 metre',
        pricePaise: 49900,
        imageFiles: ['amazon-basics-hdmi-2m-front.png', 'amazon-basics-hdmi-2m-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a coiled black HDMI cable with gold connectors visible, product studio shot, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of close-up of the same HDMI cable gold connector ends, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Portronics SoundDrum S Bluetooth Speaker',
        handle: 'portronics-sounddrum-s',
        shortDescription: '10W portable speaker with TWS pairing.',
        description: 'Deep bass, Type-C charging, and 8-hour playtime for indoor parties and outdoor picnics.',
        sku: 'GC-ELEC-PT-008',
        variantTitle: 'Black',
        pricePaise: 179900,
        imageFiles: ['portronics-sounddrum-s-front.png', 'portronics-sounddrum-s-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a cylindrical black portable drum Bluetooth speaker, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black drum speaker top-down view showing controls, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'TP-Link Archer C6 Wi-Fi Router',
        handle: 'tp-link-archer-c6-router',
        shortDescription: 'AC1200 dual-band Gigabit Wi-Fi router.',
        description: 'MU-MIMO Wi-Fi for apartments with multiple devices. Easy Tether app setup.',
        sku: 'GC-ELEC-TP-009',
        variantTitle: 'AC1200',
        pricePaise: 249900,
        imageFiles: ['tp-link-archer-c6-router-front.png', 'tp-link-archer-c6-router-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a black dual-band Wi-Fi router with four external antennas, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same Wi-Fi router rear view showing ethernet ports, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Zebronics Zeb-Transformer Gaming Keyboard',
        handle: 'zebronics-zeb-transformer-keyboard',
        shortDescription: 'RGB wired gaming keyboard with multimedia keys.',
        description: 'Durable membrane keys, LED backlight modes, and dedicated media controls for work and play.',
        sku: 'GC-ELEC-ZB-010',
        variantTitle: 'Black RGB',
        pricePaise: 139900,
        imageFiles: ['zebronics-zeb-transformer-keyboard-front.png', 'zebronics-zeb-transformer-keyboard-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a black RGB backlit gaming keyboard glowing blue-purple, front angled view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same RGB gaming keyboard from a steeper side angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
    ],
  },
  {
    name: 'Baby Playing Toys',
    slug: 'baby-playing-toys',
    products: [
      {
        title: 'Funskool Giggles Stacking Rings',
        handle: 'funskool-giggles-stacking-rings',
        shortDescription: 'Classic stacking rings for toddlers.',
        description: 'Bright rings teach colours and hand-eye coordination. BPA-free plastic safe for little hands.',
        sku: 'GC-TOY-FS-001',
        variantTitle: 'Multicolour',
        pricePaise: 34900,
        imageFiles: ['funskool-giggles-stacking-rings-front.png', 'funskool-giggles-stacking-rings-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a colorful plastic stacking ring toy with rainbow rings on a post and base, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same stacking rings toy with rings partially removed beside the post, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Melissa & Doug Wooden Building Blocks',
        handle: 'melissa-doug-wooden-blocks',
        shortDescription: '100-piece wooden block set for creative play.',
        description: 'Smooth solid-wood blocks in multiple shapes to build towers, towns, and early STEM skills.',
        sku: 'GC-TOY-MD-002',
        variantTitle: '100 pcs',
        pricePaise: 249900,
        imageFiles: ['melissa-doug-wooden-blocks-front.png', 'melissa-doug-wooden-blocks-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a neat pile of colorful wooden building blocks in mixed shapes, studio product photo, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same wooden blocks arranged into a small tower from another angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Fisher-Price Laugh & Learn Puppy',
        handle: 'fisher-price-laugh-learn-puppy',
        shortDescription: 'Interactive learning plush puppy.',
        description: 'Songs, phrases, and soft textures introduce first words, colours, and emotions for ages 6M+.',
        sku: 'GC-TOY-FP-003',
        variantTitle: 'Soft Plush',
        pricePaise: 199900,
        imageFiles: ['fisher-price-laugh-learn-puppy-front.png', 'fisher-price-laugh-learn-puppy-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a soft beige interactive learning plush puppy toy sitting upright, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same plush puppy toy from the side showing ears and paws, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Lego Duplo My First Number Train',
        handle: 'lego-duplo-number-train',
        shortDescription: 'Chunky Duplo train for number learning.',
        description: 'Build-and-play train that teaches counting 1–10. Compatible with other Duplo sets.',
        sku: 'GC-TOY-LD-004',
        variantTitle: 'Ages 1.5+',
        pricePaise: 179900,
        imageFiles: ['lego-duplo-number-train-front.png', 'lego-duplo-number-train-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a chunky colorful Duplo-style number train toy with numbered cars, front three-quarter view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same number train toy from the opposite side angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Hot Wheels 5-Car Gift Pack',
        handle: 'hot-wheels-5-car-gift-pack',
        shortDescription: 'Die-cast vehicle pack for imaginative play.',
        description: 'Five authentic Hot Wheels cars with metal bodies and rolling wheels. Collect and race.',
        sku: 'GC-TOY-HW-005',
        variantTitle: '5 Cars',
        pricePaise: 79900,
        imageFiles: ['hot-wheels-5-car-gift-pack-front.png', 'hot-wheels-5-car-gift-pack-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of five colorful die-cast toy cars lined up on white background, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same five die-cast toy cars arranged in a V formation from above, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Hasbro Monopoly Junior',
        handle: 'hasbro-monopoly-junior',
        shortDescription: 'Kid-friendly Monopoly board game.',
        description: 'Simplified money and property rules for ages 5+. Builds counting and turn-taking skills.',
        sku: 'GC-TOY-HB-006',
        variantTitle: 'Junior Edition',
        pricePaise: 89900,
        imageFiles: ['hasbro-monopoly-junior-front.png', 'hasbro-monopoly-junior-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a Monopoly Junior board game box standing upright with colorful kid artwork, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same Monopoly Junior box angled open showing board and pieces inside, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Chicco Baby Sense Soft Ball',
        handle: 'chicco-baby-sense-soft-ball',
        shortDescription: 'Textured sensory soft ball.',
        description: 'Soft fabric panels with crinkle sounds and loops to develop grip and sensory curiosity.',
        sku: 'GC-TOY-CH-007',
        variantTitle: 'Soft Ball',
        pricePaise: 59900,
        imageFiles: ['chicco-baby-sense-soft-ball-front.png', 'chicco-baby-sense-soft-ball-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a multicolored soft fabric sensory baby ball with textured panels and ribbons, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same soft sensory ball from another angle showing loops and fabrics, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Barbie Dreamhouse Adventures Doll',
        handle: 'barbie-dreamhouse-adventures-doll',
        shortDescription: 'Fashion doll with poseable joints.',
        description: 'Inspires storytelling and dress-up play. Includes styled outfit ready for adventures.',
        sku: 'GC-TOY-BB-008',
        variantTitle: 'Doll',
        pricePaise: 129900,
        imageFiles: ['barbie-dreamhouse-adventures-doll-front.png', 'barbie-dreamhouse-adventures-doll-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a fashion doll with long hair wearing a casual pink outfit standing on a stand, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same fashion doll from a three-quarter back angle showing hair and outfit, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Nerf Elite Junior Easy-Play Blaster',
        handle: 'nerf-elite-junior-blaster',
        shortDescription: 'Easy-pump foam dart blaster for kids.',
        description: 'Designed for smaller hands with soft tip darts. Great for supervised outdoor play.',
        sku: 'GC-TOY-NF-009',
        variantTitle: 'Junior',
        pricePaise: 149900,
        imageFiles: ['nerf-elite-junior-blaster-front.png', 'nerf-elite-junior-blaster-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a blue and orange junior foam dart blaster toy with soft tip darts, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same foam dart blaster side profile with a dart loaded, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Penguin Random House Board Book Set',
        handle: 'penguin-board-book-set-animals',
        shortDescription: 'First words animal board book trio.',
        description: 'Thick pages and colourful animal illustrations for bedtime reading with toddlers.',
        sku: 'GC-TOY-BK-010',
        variantTitle: '3 Books',
        pricePaise: 69900,
        imageFiles: ['penguin-board-book-set-animals-front.png', 'penguin-board-book-set-animals-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a set of three colorful animal board books for toddlers stacked neatly, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same three board books fanned open showing illustrated animal pages, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
    ],
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    products: [
      {
        title: 'Decathlon DOMYOS 5kg Dumbbell Pair',
        handle: 'domyos-5kg-dumbbell-pair',
        shortDescription: 'Hex rubber dumbbells for home workouts.',
        description: 'Floor-friendly hex design that will not roll. Ideal for strength training at home.',
        sku: 'GC-SPRT-DB-001',
        variantTitle: '5 kg Pair',
        pricePaise: 149900,
        imageFiles: ['domyos-5kg-dumbbell-pair-front.png', 'domyos-5kg-dumbbell-pair-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a pair of black hex rubber 5kg dumbbells side by side, front studio view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same hex dumbbells stacked and angled to show end plates, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Nivia Storm Football Size 5',
        handle: 'nivia-storm-football-size-5',
        shortDescription: 'Match football with soft PU cover.',
        description: 'Machine-stitched size 5 ball for turf and ground practice. Balanced bounce and grip.',
        sku: 'GC-SPRT-FB-002',
        variantTitle: 'Size 5',
        pricePaise: 79900,
        imageFiles: ['nivia-storm-football-size-5-front.png', 'nivia-storm-football-size-5-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a classic white and black paneled size 5 football, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same football from a rotated angle showing panel stitching, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Yonex GR 303 Badminton Racquet',
        handle: 'yonex-gr-303-badminton-racquet',
        shortDescription: 'Lightweight aluminium badminton racquet.',
        description: 'Beginner-friendly balance and durable steel shaft for club and school play. Includes cover.',
        sku: 'GC-SPRT-YN-003',
        variantTitle: 'Strung',
        pricePaise: 69900,
        imageFiles: ['yonex-gr-303-badminton-racquet-front.png', 'yonex-gr-303-badminton-racquet-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a blue aluminium badminton racquet with strung head standing vertically, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same badminton racquet angled showing throat and grip, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Cosco Volleyball Training Ball',
        handle: 'cosco-volleyball-training',
        shortDescription: 'Soft-touch volleyball for indoor training.',
        description: 'Reliable panel construction for school tournaments and beach practice.',
        sku: 'GC-SPRT-CS-004',
        variantTitle: 'Official Size',
        pricePaise: 64900,
        imageFiles: ['cosco-volleyball-training-front.png', 'cosco-volleyball-training-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a yellow and blue soft-touch volleyball, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same volleyball rotated showing panel pattern, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Strauss Yoga Mat 6mm',
        handle: 'strauss-yoga-mat-6mm',
        shortDescription: 'Non-slip 6mm yoga mat with carry strap.',
        description: 'Extra cushioning for joints during yoga, pilates, and floor workouts. Easy to wipe clean.',
        sku: 'GC-SPRT-YG-005',
        variantTitle: 'Purple 6mm',
        pricePaise: 89900,
        imageFiles: ['strauss-yoga-mat-6mm-front.png', 'strauss-yoga-mat-6mm-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a rolled purple 6mm yoga mat with carry strap, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same purple yoga mat partially unrolled on white background, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'HRX Active Training T-Shirt',
        handle: 'hrx-active-training-tshirt',
        shortDescription: 'Moisture-wicking training tee.',
        description: 'Breathable fabric keeps you dry through HIIT and runs. Regular fit for men.',
        sku: 'GC-SPRT-HRX-006',
        variantTitle: 'M / Men',
        pricePaise: 79900,
        imageFiles: ['hrx-active-training-tshirt-front.png', 'hrx-active-training-tshirt-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a folded charcoal grey moisture-wicking athletic t-shirt, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same athletic t-shirt laid flat showing short sleeves and crew neck, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Wildcraft HypaShield Outdoor Backpack 30L',
        handle: 'wildcraft-30l-outdoor-backpack',
        shortDescription: '30L daypack for gym and day hikes.',
        description: 'Multiple compartments, bottle pockets, and padded straps for daily carry.',
        sku: 'GC-SPRT-WC-007',
        variantTitle: '30 L',
        pricePaise: 199900,
        imageFiles: ['wildcraft-30l-outdoor-backpack-front.png', 'wildcraft-30l-outdoor-backpack-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a black 30 litre outdoor daypack backpack upright, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black backpack back view showing padded straps, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Boldfit Resistance Band Set',
        handle: 'boldfit-resistance-band-set',
        shortDescription: 'Latex resistance bands with door anchor.',
        description: 'Five resistance levels for strength and mobility workouts anywhere at home.',
        sku: 'GC-SPRT-BF-008',
        variantTitle: '5 Bands',
        pricePaise: 69900,
        imageFiles: ['boldfit-resistance-band-set-front.png', 'boldfit-resistance-band-set-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a set of five colorful latex resistance bands with handles and door anchor, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same resistance band set arranged in a neat coil from another angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'SG Club Kashmir Willow Cricket Bat',
        handle: 'sg-club-kashmir-willow-bat',
        shortDescription: 'Kashmir willow bat for club cricket.',
        description: 'Lightweight pickup with thick edges. Includes toe guard and bat cover.',
        sku: 'GC-SPRT-SG-009',
        variantTitle: 'Full Size SH',
        pricePaise: 249900,
        imageFiles: ['sg-club-kashmir-willow-bat-front.png', 'sg-club-kashmir-willow-bat-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a Kashmir willow cricket bat with grip and toe guard, front face view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same cricket bat edge-on side profile view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Puma Running Shorts DryCELL',
        handle: 'puma-running-shorts-drycell',
        shortDescription: 'Lightweight DryCELL running shorts.',
        description: 'Sweat-wicking fabric and elastic waistband for humid-weather runs.',
        sku: 'GC-SPRT-PM-010',
        variantTitle: 'M / Men',
        pricePaise: 129900,
        imageFiles: ['puma-running-shorts-drycell-front.png', 'puma-running-shorts-drycell-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of black lightweight running shorts with elastic waistband folded neatly, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same black running shorts laid flat showing inseam and waistband, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
    ],
  },
  {
    name: 'Perfumes',
    slug: 'perfumes',
    products: [
      {
        title: 'Engage Yin Eau de Parfum for Men',
        handle: 'engage-yin-edp-men',
        shortDescription: 'Fresh woody EDP for daily wear.',
        description: 'Citrus top notes with a warm woody base. Long-lasting office-friendly fragrance.',
        sku: 'GC-PERF-EN-001',
        variantTitle: '100 ml',
        pricePaise: 39900,
        imageFiles: ['engage-yin-edp-men-front.png', 'engage-yin-edp-men-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of a sleek black men's eau de parfum spray bottle 100ml, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same black perfume bottle from a three-quarter angled view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Skinn by Titan Celeste for Women',
        handle: 'skinn-titan-celeste-women',
        shortDescription: 'Floral fruity eau de parfum.',
        description: 'Elegant bouquet of florals with a soft musk dry-down. Ideal for evenings and celebrations.',
        sku: 'GC-PERF-SK-002',
        variantTitle: '50 ml',
        pricePaise: 179900,
        imageFiles: ['skinn-titan-celeste-women-front.png', 'skinn-titan-celeste-women-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of an elegant pink-gold women's perfume bottle with floral accents, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same pink-gold perfume bottle side angle showing spray nozzle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Wild Stone Ultra Sensual Deodorant',
        handle: 'wild-stone-ultra-sensual-deo',
        shortDescription: 'Long-lasting body deodorant for men.',
        description: 'Bold aromatic scent that keeps you fresh through long days. No gas spray.',
        sku: 'GC-PERF-WS-003',
        variantTitle: '150 ml',
        pricePaise: 22500,
        imageFiles: ['wild-stone-ultra-sensual-deo-front.png', 'wild-stone-ultra-sensual-deo-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of a tall black men's deodorant body spray can, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same black deodorant can from a slight side angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'The Body Shop White Musk EDT',
        handle: 'body-shop-white-musk-edt',
        shortDescription: 'Clean classic musk eau de toilette.',
        description: 'Soft powdery musk loved across generations. Layer with matching body mist.',
        sku: 'GC-PERF-TBS-004',
        variantTitle: '60 ml',
        pricePaise: 249900,
        imageFiles: ['body-shop-white-musk-edt-front.png', 'body-shop-white-musk-edt-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a white frosted glass musk eau de toilette bottle, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same white musk perfume bottle with cap beside it, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Ajmal Evoke Gold for Him',
        handle: 'ajmal-evoke-gold-him',
        shortDescription: 'Oriental spicy EDP for men.',
        description: 'Rich Middle-Eastern inspired blend with amber warmth. Statement evening fragrance.',
        sku: 'GC-PERF-AJ-005',
        variantTitle: '90 ml',
        pricePaise: 199900,
        imageFiles: ['ajmal-evoke-gold-him-front.png', 'ajmal-evoke-gold-him-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of a luxurious gold and black oriental men's perfume bottle, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same gold black perfume bottle angled three-quarter view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Lattafa Asad Eau de Parfum',
        handle: 'lattafa-asad-edp',
        shortDescription: 'Bold vanilla-woody unisex EDP.',
        description: 'Popular long-wear scent with sweet vanilla and smoky woods. Great value prestige feel.',
        sku: 'GC-PERF-LT-006',
        variantTitle: '100 ml',
        pricePaise: 189900,
        imageFiles: ['lattafa-asad-edp-front.png', 'lattafa-asad-edp-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a dark ornate unisex eau de parfum bottle with gold accents, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', 'Photorealistic ecommerce product photography of the same ornate perfume bottle from the opposite three-quarter angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Park Avenue Good Morning Perfume Spray',
        handle: 'park-avenue-good-morning',
        shortDescription: 'Fresh morning fragrance spray for men.',
        description: 'Crisp aquatic notes for a clean start to the day. Easy everyday spray.',
        sku: 'GC-PERF-PA-007',
        variantTitle: '100 ml',
        pricePaise: 29900,
        imageFiles: ['park-avenue-good-morning-front.png', 'park-avenue-good-morning-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of a blue men's morning fragrance spray bottle, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same blue fragrance spray bottle side view, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Bella Vita Organic CEO Woman EDP',
        handle: 'bella-vita-ceo-woman-edp',
        shortDescription: 'Modern floral EDP crafted in India.',
        description: 'Bright florals with a confident dry-down. Alcohol-based long-lasting formula.',
        sku: 'GC-PERF-BV-008',
        variantTitle: '100 ml',
        pricePaise: 54900,
        imageFiles: ['bella-vita-ceo-woman-edp-front.png', 'bella-vita-ceo-woman-edp-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of a modern rose-gold women's EDP bottle labeled style minimal, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same rose-gold perfume bottle rear three-quarter angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Guess 1981 Eau de Toilette Women',
        handle: 'guess-1981-edt-women',
        shortDescription: 'Soft floral EDT for everyday elegance.',
        description: 'Light floral-woody trail perfect for daytime and brunch looks.',
        sku: 'GC-PERF-GS-009',
        variantTitle: '100 ml',
        pricePaise: 299900,
        imageFiles: ['guess-1981-edt-women-front.png', 'guess-1981-edt-women-angle.png'],
        imagePrompts: ["Photorealistic ecommerce product photography of a clear glass women's EDT bottle with soft silver cap, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style", 'Photorealistic ecommerce product photography of the same clear EDT bottle lying diagonally with cap on, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style'],
      },
      {
        title: 'Beardo Godfather Perfume for Men',
        handle: 'beardo-godfather-perfume',
        shortDescription: 'Smoky tobacco-leather masculine scent.',
        description: 'Bold evening fragrance with tobacco, leather, and spice. Made for winter nights.',
        sku: 'GC-PERF-BD-010',
        variantTitle: '100 ml',
        pricePaise: 149900,
        imageFiles: ['beardo-godfather-perfume-front.png', 'beardo-godfather-perfume-angle.png'],
        imagePrompts: ['Photorealistic ecommerce product photography of a dark masculine tobacco-leather perfume bottle with matte black finish, front view, front three-quarter view, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style', "Photorealistic ecommerce product photography of the same matte black men's perfume bottle from a dramatic side angle, different camera angle, isolated on a pure white seamless studio background, soft professional lighting, sharp focus, high detail, no people, no hands, no text overlay, no watermark, commercial catalog style"],
      },
    ],
  },
] as const;

export const GLOBAL_CATALOG_EXPECTED = {
  categories: 6,
  products: 60,
  images: 120,
} as const;

export const GLOBAL_CATALOG_MEDIA_DIR = "global-catalog-media";
